### ISSUE TITLE
Nested /*...*/ comments break module (closes comment block)

### ISSUE THREAD

**Issue by zidsi** [Polymer/polymer-modulizer#333] opened 2018-02-16 14:26 UTC
Playing with [Polymer 3.0 preview](https://github.com/Polymer/polymer/tree/3.0-preview) run into issue with "modulized" [app-grid-style](https://github.com/PolymerElements/app-layout/blob/master/app-grid/app-grid-style.html#L84).

Looks like modulizer converts HTML comment blocks `<!-- ... -->` to JS comment blocks `/** ... */`, but fails to handle pre-existing `/*  ... */` blocks in `<!-- ... -->` block. 

It results with comment block being "closed" by nested comment block and further (originally commented) part is interpreted as JS code. 

Replacing (nested) comment closing tag  `*/` with `&#42;/` would probably solve the issue (at least in this case).

**Comment by TimvdLippe** [comment] 2018-02-16 14:28
This is a duplicate of #321 which has been fixed in #322. The 3.0-preview branch should be updated soon to reflect these fixes.

**Closed by TimvdLippe** 2018-02-16 14:28 UTC

**Comment by stramel** [comment] 2018-02-16 14:38
@TimvdLippe `__auto_generated_3.0_preview` is the updated branch not to be confused with the previously used branch `3.0-preview`

**Comment by zidsi** [comment] 2018-02-16 15:34
Took me a while to locate "latest"... issue persists in [__auto_generated_3.0_preview](https://github.com/PolymerElements/app-layout/blob/__auto_generated_3.0_preview/app-grid/app-grid-style.js#L163). 

I guess next successful commit will fix it according to #322, since  last (unsuccessful commit) tried to fix the issue by replacing `*/` with `*\/`. If that content is going to be used as HTML rendered (docs) suggested replacement with `&#42;/` would probably make more sense. But both will do the trick. 

It's closed regarding modulizer ;)
